param(
    [string]$ConfigPath = "",
    [string]$VaultRoot = "D:\Obsidian\projects",
    [ValidateSet("safe", "mirror")]
    [string]$SyncMode = "safe"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

. (Join-Path $PSScriptRoot "Resolve-HubIndexStem.ps1")

function Ensure-Directory {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }
}

function Escape-YamlDoubleQuotedValue {
    param([string]$Text)
    if ($null -eq $Text) {
        return ''
    }
    $clean = ($Text -replace "`r`n", ' ' -replace "`r", ' ' -replace "`n", ' ')
    return (($clean -replace '\\', '\\\\') -replace '"', '\"')
}

function Write-ProjectDocIndex {
    param(
        [string]$TargetDocsRoot,
        [string]$Slug,
        [string]$RepoPath,
        [string]$DisplayName = "",
        [string]$HubFileStem = ""
    )

    $updatedAt = (Get-Date).ToString("s")
    $safeRepoPath = $RepoPath.Replace("\", "\\")
    $hubStem = Get-HubIndexStem -Slug $Slug -DisplayName $DisplayName -HubFileStem $HubFileStem
    $indexPath = Join-Path $TargetDocsRoot ($hubStem + ".md")
    $readmePath = Join-Path $TargetDocsRoot "README.md"
    $hubTitle = if (-not [string]::IsNullOrWhiteSpace($DisplayName)) { $DisplayName } else { $Slug }

    $dashProjects = "$Slug/docs/obsidian/dashboards/projects-overview"
    $dashJournal = "$Slug/docs/obsidian/dashboards/commit-journal-overview"
    $dashDaily = "$Slug/docs/obsidian/dashboards/daily-log-overview"
    $templatesRoot = "$Slug/docs/obsidian/templates"

    $links = @()
    $links += "- '[[" + $Slug + "/docs]]'"
    $links += "- '[[" + $dashProjects + "]]'"
    $links += "- '[[" + $dashJournal + "]]'"
    if (Test-Path -LiteralPath $readmePath) {
        $links += "- '[[" + $Slug + "/docs/README]]'"
    }

    $content = New-Object System.Collections.Generic.List[string]
    $null = $content.Add('---')
    $null = $content.Add('type: project-doc')
    $null = $content.Add('hub: true')
    $null = $content.Add("project: $Slug")
    if (-not [string]::IsNullOrWhiteSpace($DisplayName)) {
        $dq = Escape-YamlDoubleQuotedValue -Text $DisplayName
        $null = $content.Add('display_name: "' + $dq + '"')
    }
    $null = $content.Add("source_repo: $Slug")
    $null = $content.Add("source_repo_path: $safeRepoPath")
    $null = $content.Add("updated_at: $updatedAt")
    $null = $content.Add('tags: [project-doc, vault-sync, hub]')
    $null = $content.Add('links:')

    foreach ($link in $links) {
        $null = $content.Add($link)
    }

    # Avoid `[[...]]` inside double-quoted literals (PowerShell type-parser); build lines with concatenation.
    $body = New-Object System.Collections.Generic.List[string]
    $null = $body.Add('---')
    $null = $body.Add('')
    $null = $body.Add("# $hubTitle - project docs hub (vault sync)")
    $null = $body.Add('')
    $null = $body.Add('Synced `docs` from the repo into this vault folder. Use dashboards below for Dataview.')
    $null = $body.Add('')
    $null = $body.Add('## Dataview dashboards')
    $null = $body.Add('- [[' + $dashProjects + '|Projects overview]]')
    $null = $body.Add('- [[' + $dashJournal + '|Commit journal overview]]')
    $null = $body.Add('- [[' + $dashDaily + '|Daily log overview]]')
    $null = $body.Add('')
    $null = $body.Add('## Templates')
    $null = $body.Add('- [[' + $templatesRoot + '|Templates folder]] (daily / project)')
    $null = $body.Add('')
    $null = $body.Add('## Quick links')
    $null = $body.Add('- [[' + $Slug + '/docs|Synced docs root]]')
    $null = $body.Add('- [[' + $Slug + '/docs/obsidian/dashboards/commit-journal-overview|Commit journals (Dataview)]]')
    $null = $body.Add('- [[' + $Slug + '/docs/obsidian/README|Obsidian kit notes]]')
    $null = $body.Add('')
    $null = $body.Add('## Meta')
    $null = $body.Add('- Generated by: `scripts/obsidian/sync-docs.ps1` (`Write-ProjectDocIndex`)')
    $null = $body.Add("- Last synced: $updatedAt")

    foreach ($line in $body) {
        $null = $content.Add($line)
    }

    Set-Content -LiteralPath $indexPath -Value ($content -join "`r`n") -Encoding UTF8

    $legacyHub = Join-Path $TargetDocsRoot "_project-doc-index.md"
    if ($hubStem -ne '_project-doc-index' -and (Test-Path -LiteralPath $legacyHub)) {
        Remove-Item -LiteralPath $legacyHub -Force
    }
}

function Resolve-DocsPaths {
    param(
        [object[]]$DocsPaths
    )

    if (-not $DocsPaths -or $DocsPaths.Count -eq 0) {
        return @("docs")
    }

    return $DocsPaths
}

function Resolve-SyncMode {
    param(
        [string]$Candidate,
        [string]$Fallback = "safe"
    )

    $value = if ($null -eq $Candidate) { "" } else { $Candidate.Trim().ToLowerInvariant() }
    if ($value -eq "safe" -or $value -eq "mirror") {
        return $value
    }

    $fallbackValue = if ($null -eq $Fallback) { "safe" } else { $Fallback.Trim().ToLowerInvariant() }
    if ($fallbackValue -eq "safe" -or $fallbackValue -eq "mirror") {
        return $fallbackValue
    }

    return "safe"
}

function Resolve-GitRepoRoot {
    param([string]$FallbackPath)

    $previousErrorPreference = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    $repoRoot = & git -C $FallbackPath rev-parse --show-toplevel 2>$null
    $ErrorActionPreference = $previousErrorPreference

    if ($LASTEXITCODE -eq 0 -and -not [string]::IsNullOrWhiteSpace($repoRoot)) {
        return ($repoRoot -join "`n").Trim()
    }

    return $FallbackPath
}

function Ensure-ObsidianIngestConfig {
    param(
        [string]$RepoPath,
        [string]$DefaultVaultRoot = "D:\Obsidian\projects",
        [string]$DefaultSyncMode = "safe"
    )

    $ingestPath = Join-Path $RepoPath ".obsidian-ingest.json"
    $folderSlug = Split-Path -Path $RepoPath -Leaf
    $vaultRoot = $DefaultVaultRoot
    $docsPaths = @("docs")
    $syncMode = Resolve-SyncMode -Candidate $DefaultSyncMode -Fallback "safe"
    $lockSlug = $false
    $cfg = $null
    $hadReadableFile = $false

    if (Test-Path -LiteralPath $ingestPath) {
        try {
            $raw = Get-Content -LiteralPath $ingestPath -Raw -Encoding UTF8
            if (-not [string]::IsNullOrWhiteSpace($raw)) {
                $cfg = $raw | ConvertFrom-Json
                $hadReadableFile = $true
            }
        } catch {
            $cfg = $null
            $hadReadableFile = $false
        }
    }

    if ($null -ne $cfg) {
        if (-not [string]::IsNullOrWhiteSpace($cfg.vaultRoot)) {
            $vaultRoot = [string]$cfg.vaultRoot
        }
        if ($cfg.docsPaths -and @($cfg.docsPaths).Count -gt 0) {
            $docsPaths = @($cfg.docsPaths | ForEach-Object { [string]$_ })
        }
        $syncProp = $cfg.PSObject.Properties['syncMode']
        if ($null -ne $syncProp -and -not [string]::IsNullOrWhiteSpace([string]$syncProp.Value)) {
            $syncMode = Resolve-SyncMode -Candidate ([string]$syncProp.Value) -Fallback $syncMode
        }
        $lockProp = $cfg.PSObject.Properties['lockSlug']
        if ($null -ne $lockProp -and $null -ne $lockProp.Value) {
            $lockSlug = [bool]$lockProp.Value
        }
    }

    $slug = $folderSlug
    $mustWrite = -not $hadReadableFile
    if ($hadReadableFile -and $null -ne $cfg) {
        $existingSlug = [string]$cfg.slug
        if (-not $lockSlug -and $existingSlug -ne $folderSlug) {
            $mustWrite = $true
        }
    }

    if (-not $mustWrite) {
        return
    }

    $out = [pscustomobject]@{
        slug       = $slug
        lockSlug   = $lockSlug
        vaultRoot  = $vaultRoot
        docsPaths  = $docsPaths
        syncMode   = $syncMode
    }
    $json = $out | ConvertTo-Json -Depth 6
    Set-Content -LiteralPath $ingestPath -Value $json -Encoding utf8
    Write-Host "Wrote or repaired: $ingestPath (slug=$slug, lockSlug=$lockSlug, syncMode=$syncMode)"
}

function Get-AutoRepositoryEntry {
    $projectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
    $repoPath = Resolve-GitRepoRoot -FallbackPath $projectRoot
    Ensure-ObsidianIngestConfig -RepoPath $repoPath -DefaultSyncMode $script:SyncMode

    $slug = Split-Path -Path $repoPath -Leaf
    $docsPaths = @("docs")
    $repoSyncMode = Resolve-SyncMode -Candidate $script:SyncMode -Fallback "safe"

    $displayName = ""
    $hubFileStem = ""
    $ingestConfigPath = Join-Path $repoPath ".obsidian-ingest.json"
    if (Test-Path -LiteralPath $ingestConfigPath) {
        $repoConfig = Get-Content -LiteralPath $ingestConfigPath -Raw -Encoding UTF8 | ConvertFrom-Json
        if ($repoConfig.slug) {
            $slug = [string]$repoConfig.slug
        }
        if ($repoConfig.vaultRoot) {
            $script:VaultRoot = [string]$repoConfig.vaultRoot
        }
        if ($repoConfig.docsPaths -and $repoConfig.docsPaths.Count -gt 0) {
            $docsPaths = @($repoConfig.docsPaths)
        }
        $smProp = $repoConfig.PSObject.Properties['syncMode']
        if ($null -ne $smProp -and -not [string]::IsNullOrWhiteSpace([string]$smProp.Value)) {
            $repoSyncMode = Resolve-SyncMode -Candidate ([string]$smProp.Value) -Fallback $repoSyncMode
        }
        $dnProp = $repoConfig.PSObject.Properties['displayName']
        if ($null -ne $dnProp -and -not [string]::IsNullOrWhiteSpace([string]$dnProp.Value)) {
            $displayName = [string]$dnProp.Value
        }
        $hfProp = $repoConfig.PSObject.Properties['hubFileStem']
        if ($null -ne $hfProp -and -not [string]::IsNullOrWhiteSpace([string]$hfProp.Value)) {
            $hubFileStem = [string]$hfProp.Value
        }
    }

    return @([pscustomobject]@{
        path         = $repoPath
        slug         = $slug
        docsPaths    = $docsPaths
        syncMode     = $repoSyncMode
        displayName  = $displayName
        hubFileStem  = $hubFileStem
    })
}

$repositories = @()
if ([string]::IsNullOrWhiteSpace($ConfigPath)) {
    $repositories = Get-AutoRepositoryEntry
} else {
    if (-not (Test-Path -LiteralPath $ConfigPath)) {
        throw "Config file not found: $ConfigPath"
    }

    $config = Get-Content -LiteralPath $ConfigPath -Raw | ConvertFrom-Json
    if (-not $config.repositories -or $config.repositories.Count -eq 0) {
        throw "No repositories configured in $ConfigPath"
    }
    $repositories = @($config.repositories)
}

$vaultProjectsRoot = $VaultRoot
Ensure-Directory -Path $vaultProjectsRoot

foreach ($repo in $repositories) {
    if (-not $repo.path -or -not $repo.slug) {
        Write-Warning "Skipping invalid entry (missing path/slug)."
        continue
    }

    $repoPath = [string]$repo.path
    $slug = [string]$repo.slug
    $docsPaths = Resolve-DocsPaths -DocsPaths $repo.docsPaths
    $repoSyncMode = Resolve-SyncMode -Candidate ([string]$repo.syncMode) -Fallback $SyncMode
    $displayName = ""
    $repoDn = $repo.PSObject.Properties['displayName']
    if ($null -ne $repoDn -and -not [string]::IsNullOrWhiteSpace([string]$repoDn.Value)) {
        $displayName = [string]$repoDn.Value
    }
    $hubFileStem = ""
    $hfRepo = $repo.PSObject.Properties['hubFileStem']
    if ($null -ne $hfRepo -and -not [string]::IsNullOrWhiteSpace([string]$hfRepo.Value)) {
        $hubFileStem = [string]$hfRepo.Value
    }

    if (-not (Test-Path -LiteralPath $repoPath)) {
        Write-Warning "Repo path not found, skipping: $repoPath"
        continue
    }

    $targetRepoRoot = Join-Path $vaultProjectsRoot $slug
    $targetDocsRoot = Join-Path $targetRepoRoot "docs"
    Ensure-Directory -Path $targetDocsRoot

    foreach ($relativeDocPath in $docsPaths) {
        $sourcePath = Join-Path $repoPath ([string]$relativeDocPath)
        if (-not (Test-Path -LiteralPath $sourcePath)) {
            Write-Warning "Docs path missing, skipping: $sourcePath"
            continue
        }

        # Normalize: primary "docs" folder mirrors to <vault>/<slug>/docs/ (no .../docs/docs)
        $relNorm = ([string]$relativeDocPath).Trim().Replace("/", "\")
        while ($relNorm.StartsWith(".\")) {
            $relNorm = $relNorm.Substring(2)
        }
        $relNorm = $relNorm.TrimEnd("\")

        $targetPath = $null
        if ($relNorm -ieq "docs") {
            $targetPath = $targetDocsRoot
        } else {
            $leaf = Split-Path -Path $relNorm -Leaf
            if ([string]::IsNullOrWhiteSpace($leaf)) {
                $leaf = "docs"
            }
            $targetPath = Join-Path $targetDocsRoot $leaf
        }

        Ensure-Directory -Path $targetPath

        $robocopyOptions = @('/R:1', '/W:1', '/NFL', '/NDL', '/NJH', '/NJS', '/NP')
        if ($repoSyncMode -eq 'mirror') {
            # mirror: destination entries not present in source are deleted.
            $robocopyOptions = @('/MIR') + $robocopyOptions
        } else {
            # safe: copy recursively without deleting destination-only files.
            $robocopyOptions = @('/E') + $robocopyOptions
        }
        robocopy $sourcePath $targetPath @robocopyOptions | Out-Null
        $exitCode = $LASTEXITCODE
        if ($exitCode -ge 8) {
            throw "robocopy failed for '$sourcePath' -> '$targetPath' (exit code: $exitCode)"
        }

        Write-Host "Synced($repoSyncMode): $sourcePath -> $targetPath"
    }

    Write-ProjectDocIndex -TargetDocsRoot $targetDocsRoot -Slug $slug -RepoPath $repoPath -DisplayName $displayName -HubFileStem $hubFileStem
    Write-Host "Indexed: $targetDocsRoot"
}

Write-Host "Done. Docs synced into: $vaultProjectsRoot"
